#!/bin/bash
# Clean script - removes all files generated by genkernels.py
# This is useful for regenerating kernels from updated tuning results

echo "=========================================="
echo "CLEAN SCRIPT - Remove Generated Files"
echo "=========================================="
echo ""
echo "This will remove all files generated by genkernels.py:"
echo ""
echo "Directories:"
echo "  - kernels/"
echo "  - kernel_outputs/"
echo "  - build/"
echo "  - scripts/"
echo ""
echo "Files:"
echo "  - kernel_metadata.csv"
echo "  - CMakeLists.txt"
echo "  - run_all.sh"
echo "  - run_layer_*.sh (all layer scripts)"
echo ""
echo "This will NOT remove:"
echo "  - tuningresults/ (tuning data)"
echo "  - tuningrecords/ (raw tuning data)"
echo "  - Source files (*.py, *.cpp, *.cu templates)"
echo ""
read -p "Are you sure you want to continue? (y/N) " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 0
fi

echo ""
echo "Cleaning..."

# Remove directories
if [ -d "kernels" ]; then
    echo "  Removing kernels/"
    rm -rf kernels/
fi

if [ -d "kernel_outputs" ]; then
    echo "  Removing kernel_outputs/"
    rm -rf kernel_outputs/
fi

if [ -d "build" ]; then
    echo "  Removing build/"
    rm -rf build/
fi

if [ -d "scripts" ]; then
    echo "  Removing scripts/"
    rm -rf scripts/
fi

# Remove files
if [ -f "kernel_metadata.csv" ]; then
    echo "  Removing kernel_metadata.csv"
    rm -f kernel_metadata.csv
fi

if [ -f "CMakeLists.txt" ]; then
    echo "  Removing CMakeLists.txt"
    rm -f CMakeLists.txt
fi

if [ -f "run_all.sh" ]; then
    echo "  Removing run_all.sh"
    rm -f run_all.sh
fi

# Remove all run_layer_*.sh files
if ls run_layer_*.sh 1> /dev/null 2>&1; then
    echo "  Removing run_layer_*.sh files"
    rm -f run_layer_*.sh
fi

echo ""
echo "=========================================="
echo "CLEANUP COMPLETE"
echo "=========================================="
echo ""
echo "All generated files have been removed."
echo "You can now run: python genkernels.py"
